# WPF Base Control Library
WPF_BASE_CONTROLS: set[str] = {
    "Border",
    "BulletDecorator",
    "Button",
    "Calendar",
    "Canvas",
    "CheckBox",
    "ComboBox",
    "ContextMenu",
    "DataGrid",
    "DatePicker",
    "DockPanel",
    "DocumentViewer",
    "Expander",
    "FlowDocumentPageViewer",
    "FlowDocumentReader",
    "FlowDocumentScrollViewer",
    "Frame",
    "Grid",
    "GridSplitter",
    "GroupBox",
    "Image",
    "Label",
    "ListBox",
    "ListView",
    "Menu",
    "Panel",
    "PasswordBox",
    "Popup",
    "ProgressBar",
    "PrintDialog",
    "RadioButton",
    "RepeatButton",
    "RichTextBox",
    "ScrollBar",
    "ScrollViewer",
    "Separator",
    "Slider",
    "StackPanel",
    "StatusBar",
    "TabControl",
    "TextBlock",
    "TextBox",
    "ToolBar",
    "ToolTip",
    "TreeView",
    "WrapPanel",
    "Viewbox",
}

def is_wpf_base_control(name: str) -> bool:
    return name.strip() in WPF_BASE_CONTROLS
